flows:
  onPush:
    - logYaml: "${event}"

  onPullRequest:
    - logYaml: "${event}"

triggers:
  - github:
      version: 2
      entryPoint: onPullRequest
      conditions:
        type: pull_request
        githubOrg: "aetion"
        githubRepo: "ck8s-ext"

  - github:
      version: 2
      entryPoint: onPush
      conditions:
        type: push
        githubOrg: "aetion"
        githubRepo: "ck8s-ext"
