configuration:
  runtime: concord-v2

flows:
  onPush:
    - logYaml: "${event}"

  onPullRequest:
    - logYaml: "${event}"

triggers:
  - github:
      version: 2
      entryPoint: onPullRequest
      conditions:
        type: pull_request
        githubOrg: ".*"
        githubRepo: ".*"

  - github:
      version: 2
      entryPoint: onPush
      conditions:
        type: push
        branch: ".*"
        githubOrg: ".*"
        githubRepo: ".*"
