flows:
  onPullRequest:
    - log: "Pull Request: ${event.commitId} to ${event.project}/${event.repository}"

triggers:
  - github:
      type: pull_request
      useInitiator: true
      entryPoint: onPullRequest