flows:
  onPush:
    - logYaml: "${event}"

  onPullRequest:
    - logYaml: "${event}"

triggers:
  - github:
      version: 2
      entryPoint: onPullRequest
      conditions:
        type: pull_request

  - github:
      version: 2
      entryPoint: onPush
      conditions:
        type: push
